export const COLLECT = 'COLLECT'
export const CLARIFY_TO_NEXT_ACTION = ' CLARIFY_TO_NEXT_ACTION'
export const ADD_HASHTAG = 'ADD_HASHTAG'
export const UPDATE_CURRENTLY_COLLECTION = 'UPDATE_CURRENTLY_COLLECTION'
